### ISSUE TITLE
yolov5版本

### ISSUE THREAD

**Issue by xyh1108** [CVHub520/X-AnyLabeling#105]
您好，请问yolov5最低支持哪个版本的呢？我所转化的onnx文件加载没有问题，但是点击标注并没有出现目标框。

**Comment by CVHub520** [comment]
Hi, @xyh1108 :
The default support for YOLOv5 starts from version 6.0 and onwards. If you are using a lower version, you may need to specify the anchors parameter in your configuration file. Here's an example:

```YAML
type: yolov5
...
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
...
```

If you're still experiencing issues, please package and send your ONNX file, YAML configuration file, and a sample image where you're certain the model should detect objects to the specified email address: cv_hub@163.com.

I will do our best to assist you further.

Best regards,
CVHub

**Comment by xyh1108** [comment]
感谢您的回复，按照您的提示我进行了修改，但依然遇到了这个问题，我已经将文件打包发送至您的邮箱了。

**Comment by CVHub520** [comment]
@xyh1108 , thank you for providing the files. After reviewing your case, I've identified a couple of issues:

1. Dynamic batch inference is not supported. When converting to ONNX, please ensure you set the batch_size to 1.

2. Dynamic shape is also not supported. However, X-AnyLabeling will automatically read the shape from the ONNX model, so there's no need for manual specification.

Here's a sample configuration file template for your reference:

```YAML
type: yolov5
name: yolov5s-r20230520
display_name: xxx
model_path: /path/to/best.onnx
stride: 32
nms_threshold: 0.5
confidence_threshold: 0.4
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/3
classes:
  ***
```

Please note that if you haven't modified the training framework, you should not adjust the 'stride' parameter, just kepp it by default, that was make perfert!

Feel free to make these adjustments, and if you encounter any further issues or have more questions, don't hesitate to reach out for assistance.

Best regards,
CVHub
