### ISSUE TITLE
YOLO v8 obb 旋转框 AI 模型无法加载

### ISSUE THREAD

**Issue by chenxinfeng4** [CVHub520/X-AnyLabeling#207]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/17546446/36e8e2df-9bd1-446f-a3bd-c5fffee0427a)

```yaml
# 从 model zoo 下载的 yolov8s_obb.yaml
type: yolov8_obb
name: yolov8s-obb-r20240111
display_name: YOLOv8s_obb (DOTA-v1.0) Ultralytics
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.3.0/yolov8s-obb.onnx
nms_threshold: 0.7
confidence_threshold: 0.25
classes:
  - plane
  - ship
  - storage tank
  - baseball diamond
  - tennis court
  - basketball court
  - ground track field
  - harbor
  - bridge
  - large vehicle
  - small vehicle
  - helicopter
  - roundabout
  - soccer ball field
  - swimming pool
```

我用的 X-anylabeling 版本也很新呀
