### ISSUE TITLE
加载YOLOv8自定义模型出错

### ISSUE THREAD

**Issue by wsy-yjys** [CVHub520/X-AnyLabeling#27]
![image](https://github.com/CVHub520/X-AnyLabeling/assets/78601159/eafadf4b-f044-4764-abd8-e8d645567deb)
加载YOLOv8自定义模型时出现上述错误，配置文件如下

```yaml
type: yolov8
name: YOLOv8s-parachute
display_name: YOLOv8s-parachute
model_path: E:\project\9_parachute_annotation\model\best.onnx
input_width: 640
input_height: 640
nms_threshold: 0.7
score_threshold: 0.25
confidence_threshold: 0.25
classes:
  - parachute
```
