### ISSUE TITLE
Error throwing when use custom yolov8 segment model.

### ISSUE THREAD

**Issue by doskid** [CVHub520/X-AnyLabeling#371]
Hello,

I'm attempting to utilize a custom YOLOv8 segmentation model for auto-labeling, but encountered an error in the program: "**`Error in predict_shapes: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().`**"

Could you please advise on how to resolve this issue? Thank you.

Here is my YAML file:
```
type: yolov8_seg
      name: best_segment3.onnx
      display_name: trolley_detect_segment2
      model_path: D:\pycharm project\yoloDemo\best_segment3.onnx
      nms_threshold: 0.45
      confidence_threshold: 0.25
      classes:
        - trolley
```
