### ISSUE TITLE
Feature Request: Introduce YAML Pipeline for Combining Existing and New Model Configurations

### ISSUE THREAD

**Issue by peters** [CVHub520/X-AnyLabeling#459]
As a user, I require the ability to configure a pipeline using a combination of existing models with property overrides and the addition of new model configurations.

**Proposed YAML configuration**
1. Reference existing models without overrides.
2. Reference and override properties of existing models.
3. Introduce new model into the pipeline.

```yaml
pipeline:
  - name: edge_sam-r20231213 # Use existing model without overrides

  - name: gold_yolo_s-r20231001  # Use existing model with overrides
    overrides:
      nms_threshold: 0.25

  - name: rtdetr_r50-r20230520  # Use existing model with specific class filters
    overrides:
      filter_classes:
        - person
        - bicycle
        - car
        - motorcycle

  - type: segment_anything  # Add a new model to the pipeline
    name: mobile_sam_vit_h-my-custom-model
    display_name: MobileSAM (ViT-Huge Custom)
    encoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.0/mobile_sam.encoder.onnx
    decoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.0/sam_vit_h_4b8939.decoder.onnx
    input_size: 1024
    max_width: 1024
    max_height: 682
```
