### ISSUE TITLE
用yolov8n-pose訓練完的模型，在自動標記時無法標記到物件

### ISSUE THREAD

**Issue by JW5123** [CVHub520/X-AnyLabeling#508]
作者您好，目前使用yolov8n-pose.yaml來訓練帶有兩個關鍵點及邊界框的物件，有將訓練後產生的best.pt檔轉換best.onnx並設置好yaml檔，但在自動標記時，雖然模型成功載入，但執行後卻沒有標記任何東西。

由於上述原因，有試過用yolov8n.yaml訓練只有邊界框的資料，拿訓練後的模型自動標記是有成功標記物件。另外，就是有發現使用軟體裡面預設的yolov8n或是yolov8n-pose模型測試自動標記人，是有標記到，但如果是用官網給的這兩個模型自行轉換onnx檔後在載入自動標記就無法標記到。

訓練資料是魚，有全身(邊界框)、頭尾(關鍵點)，下面是我配置模型的yaml檔

type: yolov8_pose
name: yolov8n-pose-r20240706
display_name: YOLOv8n
model_path: best.onnx
confidence_threshold: 0.5
nms_threshold: 0.6
kpt_threshold: 0.25
has_visible: true
classes:  
  zebrafish:
    - head
    - tail
   
這部分是訓練資料的配置檔
train: 'images/train/'
val:  'images/val/'
test: 'images/test/'

nc: 1
names: ["zebrafish"]

kpt_shape: [2, 3]
flip_idx: []

上面的配置檔都是按照官網的教學設定

**Comment by CVHub520** [comment]
您好，请确保以下几点：

1. `*.pt` 转 `*·onnx` 时没有设置动态batch，即`dynamic`参数应该设置为`False`（默认值）；
2. 确保的`*.yaml`配置文件格式是正确的，按照给定示例存在非法的文件内容，请注意缩进：
```yaml
type: yolov8_pose
name: yolov8n-pose-r20240706
display_name: YOLOv8n
model_path: best.onnx
confidence_threshold: 0.5
nms_threshold: 0.6
kpt_threshold: 0.25
has_visible: true
classes:
  zebrafish:
    - head
    - tail
```
