### ISSUE TITLE
Missing config : num_masks

### ISSUE THREAD

**Issue by lhkyyh** [CVHub520/X-AnyLabeling#515]
When I load my trained model, I encounter this problem：Missing config : num_masks
![1720627168099](https://github.com/CVHub520/X-AnyLabeling/assets/144432185/bfe1fcdd-4abf-4d49-ae8d-a1485cbdfd8c)

**Comment by CVHub520** [comment]
Hey there! @lhkyyh, 😄 

It seems like you are encountering an issue that raises an error: `Missing config: num_masks`.

Perhaps you can resolve this by replacing your local YAML file with the following configuration:

```yaml
type: yolov8_seg
name: yolov8hz
display_name: yolov8hz
model_path: hz.onnx
nms_threshold: 0.20
confidence_threshold: 0.20
classes:
  - '0'
  - '1'
```

Note:
- Label names starting with **numbers** should be enclosed in single quotes (`' '`).
- The `anchors` and `stride` fields are only allowed to be defined in the configuration file.

Finally, you can inspect the input and output nodes of your ONNX file using [Netron](https://netron.app/) and paste the details here.

**Comment by lhkyyh** [comment]
Thanks for the answer, the same issue occurs even though I followed the config file above, this is the input and output nodes of my ONNX file
![Uploading 1720664431114.png…]()

**Comment by lhkyyh** [comment]
images
name: images
tensor: float32[1,3,640,640]
output0
name: output0
tensor: float32[1,38,8400]
output1
name: output1
tensor: float32[1,32,160,160]

**Comment by lhkyyh** [comment]
![Uploading 1720664693797.jpg…]()

**Comment by lhkyyh** [comment]
input
images
name: images
tensor: float32[1,3,640,640]
output
output0
name: output0
tensor: float32[1,38,8400]
output1
name: output1
tensor: float32[1,32,160,160]

**Comment by CVHub520** [comment]
After testing your sending file, it seems that everything is normal. As memtion above, please using the latest source code via `git clone https://github.com/CVHub520/X-AnyLabeling.git`, and make sure your GUI is looks like below:

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/b4ef30ce-8b71-4947-affe-6ff3df2a6bf0)


Btw, an optimal piece of advice would be to set the classes as defined in your ONNX file, rather than using ‘0’ or ‘1’:

```yaml
type: yolov8_seg
name: yolov8hz
display_name: yolov8hz
model_path: hz.onnx
nms_threshold: 0.20
confidence_threshold: 0.20
classes:
  - crack
  - blocky crack

```
