### ISSUE TITLE
能否增加单目标关键点检测

### ISSUE THREAD

**Issue by ljh725** [CVHub520/X-AnyLabeling#744]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

感谢分享，现有yolo11x-pose、yolov8n-pose模型在多目标图片中会预估所有目标，能否支持增加框选机制实现对单目标的关键点检测，再次感谢。

**Comment by CVHub520** [comment]
You only need to define a single goal.

```yaml
has_visible: true
classes:
  person:
    - nose
    - left_eye
    - right_eye
    - left_ear
    - right_ear
    - left_shoulder
    - right_shoulder
    - left_elbow
    - right_elbow
    - left_wrist
    - right_wrist
    - left_hip
    - right_hip
    - left_knee
    - right_knee
    - left_ankle
    - right_ankle
```
