### ISSUE TITLE
自定义模型加载问题

### ISSUE THREAD

**Issue by lichenliang666** [CVHub520/X-AnyLabeling#779]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

您好，感谢您开发出这么优秀的工具，非常好用和方便。我使用您的这个工具，标注了几百张的图片数据。并使用这些数据进行模型微调。此工具让我在CV的路上走的更顺畅了。训练的后模型效果还可以，但还是有待提升，打算再多标注些数据。

这个时候想到 X-AnyLabeling 可以使用模型辅助标注，所以我打算让 X-AnyLabeling 加载我训练好的模型，帮着我再标注些数据。可不太顺利，遇到了下面问题。请大侠帮看看。感谢。感谢。

我的模型是使用 PaddleX 进行微调训练，使用的基础模型是 RT-DETR-L。训练后做了评估和预测还都可正常工作。训练环境是 wsl 下的 Ubuntu 24.04 使用 GPU 训练。

训练集是自己进行标注，里面只有一个类别。

然后使用 paddle2onnx 工具转换为 onnx 模型：

```bash
paddle2onnx --model_dir inference \
            --model_filename inference.pdmodel \
            --params_filename inference.pdiparams \
            --save_file ./onnx/RT-DETR-L-TY.onnx
```

RT-DETR-L-TY.yaml 配置文件内容如下：

```yaml
type: RT-DETR-L-TY.onnx
name: RT-DETR-L-TY.onnx
display_name: RT-DETR-L-TY.onnx
model_path: ./RT-DETR-L-TY.onnx
nms_threshold: 0.7
confidence_threshold: 0.25
classes:
  - crossroad
```

选择这个配置文件后，会出现下面这个提示：
![image](https://github.com/user-attachments/assets/05e2675f-07b0-45a2-804e-1d796d4393a5)
