### ISSUE TITLE
改进的yolo模型ai识别不画框

### ISSUE THREAD

**Issue by 123456com1** [CVHub520/X-AnyLabeling#874]
### Search before asking

- [x] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug
```
D:\Anaconda\envs\DL\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:115: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
2025-03-26 11:44:10,154 | INFO    | model_manager:_load_model:562 - ✅ Model loaded successfully: yolo11
```

模型文件
```yaml
type: yolo11
name: yolo11s-r20240930
display_name: yolo11 - c3k2_dcnv4-cloformer-2-lianbu
model_path: best.onnx
nms_threshold: 0.45
confidence_threshold: 0.25
classes:
  - bihe
  - shang
  - xia
  - you
  - youshangfang
  - youxiafang
  - zhangkai
  - zhengqianfang
  - zuo
  - zuoshangfang
  - zuoxiafang
```

### Information

Application Information:
    {'App name': 'X-AnyLabeling', 'App version': '2.5.4', 'Device': 'GPU'}

System Information:
    {'CPU': 'AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD',
     'CUDA': 'V11.8.89',
     'GPU': '0, NVIDIA GeForce RTX 4060 Laptop GPU, 8188',
     'Operating System': 'Windows-11-10.0.22631-SP0',
     'Python Version': '3.12.2'}

Package Information:
    {'ONNX Runtime GPU Version': None,
     'ONNX Runtime Version': '1.20.0',
     'ONNX Version': '1.16.1',
     'OpenCV Contrib Python Headless Version': '4.11.0.86',
     'PyQt5 Version': '5.15.7'}

### Link to a Reproducible Demonstration Video

![Image](https://github.com/user-attachments/assets/8afb904d-8180-4e3e-8d4f-80128de78ea8)

### Execution Mode

Source Code

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!
