### ISSUE TITLE
Error in using Custom Model to auto labeling

### ISSUE THREAD

**Issue by NOTGOOOOD** [CVHub520/X-AnyLabeling#983]
Hello, Thank you for your great work !

I have already created a custom yolo11x model following [the guidance](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/custom_model.md). 

But when I run the model to auto labeling, It reports error as below:
`| ERROR   | model_manager:predict_shapes:1997 - Error in predict_shapes: cannot access local variable 'p' where it is not associated with a value`

I am confused what's happening. I'm sure the `ONNX` model worked well. By the way, I can use the built-in model (yolo11-s) to auto labeling. 

My model yaml as below:
```yaml

type: yolo11x
name: yolo11x-r20250611
provider: Ultralytics
display_name: YOLO11x
input_width: 640
input_height: 640
model_path: path/to/model
iou_threshold: 0.45
conf_threshold: 0.25
classes:
  - person
  - rider
  - car
  - bus
  - truck
  - bike
  - motor
  
```
