### ISSUE TITLE
Error in loading custom model: Invalid config file format.

### ISSUE THREAD

**Issue by zydmtaichi** [CVHub520/X-AnyLabeling#986]
### Search before asking

- [x] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

Error raise in windows GUI which shown as "Error in loading custom model: Invalid config file format".

![Image](https://github.com/user-attachments/assets/5366b425-f17c-4d49-8250-1974aac3b155)

my yaml file content pasted as below:

```
type: yolo12
name: yolo12n-r20250514
provider: Ultralytics
display name: YOLO12n
model path: yolo12n.onnx
iou_threshold: 0.45
conf_threshold: 0.25
classes:
  - gzq
  - jlbs
  - jzq
  - lsd1
  - lsd10
  - tt10
  - tt13
  - jcq
  - pad
  - light
  - rag
  - nlbs
  - buncket
```

### Information

Operating System: win10

### Link to a Reproducible Demonstration Video

...

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zydmtaichi** [comment]
the similar issue are closed before without valid solution #533

**Comment by CVHub520** [comment]
Hi @zydmtaichi,

I noticed a potential issue in your YAML configuration file that might be causing the "Invalid config file format" error.

The keys `display name` and `model path` contain spaces. In YAML (and most configuration formats), keys are typically expected to be single words or use conventions like snake_case (e.g., `display_name`) or camelCase (e.g., `displayName`) if they consist of multiple words.

Your corrected configuration section would look like this:

```yaml
type: yolo12
name: yolo12n-r20250514
provider: Ultralytics
display_name: YOLO12nxxx  # Note the underscore here
model_path: yolo12n.onnx # Note the underscore here
iou_threshold: 0.45
conf_threshold: 0.25
classes:
  - gzq
  - jlbs
  - jzq
  - lsd1
  - lsd10
  - tt10
  - tt13
  - jcq
  - pad
  - light
  - rag
  - nlbs
  - buncket
```

This change should resolve the "Invalid config file format" error.

Hope this helps!
